services:
  valkey:
    image: docker.io/bitnami/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - "valkey_data:/bitnami/valkey/data"
    env_file:
      - .env

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres_data:/var/lib/postgres/data"

  api:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: on-failure:5
    depends_on:
      - postgres
      - valkey

volumes:
  valkey_data:
    driver: local
  postgres_data:
    driver: local
