services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  api:
    build: .
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    restart: on-failure:5
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Replace 8080 with the desired port for your application
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount your Nginx configuration file
    depends_on:
      - api # Nginx depends on the API service being available


volumes:
  postgres_data:
    driver: local
