services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - dragonflydata:/data

  api:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: on-failure:5
    depends_on:
      - postgres
      - dragonfly

volumes:
  postgres_data:
    driver: local
  dragonflydata:
    driver: local
